## Naive bayes

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from collections import OrderedDict
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC

In [ ]:
dataset = "https://raw.githubusercontent.com/kb22/Heart-Disease-Prediction/master/dataset.csv"
data = pd.read_csv(dataset)
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [ ]:
data.head()
data1 = data.drop(columns=['sex', 'target'])

data1 : merupakan data selain data sex dan target

In [ ]:
data2 = data[["sex"]]

data2 : merupakan data sex saja

In [ ]:
data2.head(303)

sex
0      1
1      1
2      0
3      1
4      0
..   ...
298    0
299    1
300    1
301    1
302    0

[303 rows x 1 columns]

karena datasex sudah berupa numerik maka tidak perlu diubah

In [ ]:
data3 = data[["target"]]

data3 : merupakan data target saja

In [ ]:
data3.head(303)

target
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

seperti pada data2 karna data3 sudah dalam bentuk angka maupun numerik jadi tidak perlu dirubah

In [ ]:
datanumeric = pd.concat([data2, data3], axis=1)

In [ ]:
Hasil = pd.concat([data1, datanumeric], axis=1)
Hasil

age  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0     63   3       145   233    1        0      150      0      2.3      0   
1     37   2       130   250    0        1      187      0      3.5      0   
2     41   1       130   204    0        0      172      0      1.4      2   
3     56   1       120   236    0        1      178      0      0.8      2   
4     57   0       120   354    0        1      163      1      0.6      2   
..   ...  ..       ...   ...  ...      ...      ...    ...      ...    ...   
298   57   0       140   241    0        1      123      1      0.2      1   
299   45   3       110   264    0        1      132      0      1.2      1   
300   68   0       144   193    1        1      141      0      3.4      1   
301   57   0       130   131    0        1      115      1      1.2      1   
302   57   1       130   236    0        0      174      0      0.0      1   

     ca  thal  sex  target  
0     0     1    1       1  
1     0     2    1       1  
2     0     2    0       1  
3     0     2    1       1  
4     0     2    0       1  
..   ..   ...  ...     ...  
298   0     3    0       0  
299   0     3    1       0  
300   2     3    1       0  
301   1     3    1       0  
302   1     2    0       0  

[303 rows x 14 columns]

#Min Max Normalisasi#

In [ ]:
dataNormalisasi = ['age',	'cp',	'trestbps',	'chol', 'thalach', 'oldpeak', 'slope', 'ca', 'thal']
FrameNormalisasi = Hasil[dataNormalisasi]
FrameNormalisasi

age  cp  trestbps  chol  thalach  oldpeak  slope  ca  thal
0     63   3       145   233      150      2.3      0   0     1
1     37   2       130   250      187      3.5      0   0     2
2     41   1       130   204      172      1.4      2   0     2
3     56   1       120   236      178      0.8      2   0     2
4     57   0       120   354      163      0.6      2   0     2
..   ...  ..       ...   ...      ...      ...    ...  ..   ...
298   57   0       140   241      123      0.2      1   0     3
299   45   3       110   264      132      1.2      1   0     3
300   68   0       144   193      141      3.4      1   2     3
301   57   0       130   131      115      1.2      1   1     3
302   57   1       130   236      174      0.0      1   1     2

[303 rows x 9 columns]

In [ ]:
scaler = MinMaxScaler()

In [ ]:
scaler.fit(FrameNormalisasi)

MinMaxScaler()

In [ ]:
hasilNormalisasi = scaler.transform(FrameNormalisasi)

In [ ]:
hasilNormalisasi = pd.DataFrame(hasilNormalisasi,columns = dataNormalisasi)
hasilNormalisasi

age        cp  trestbps      chol   thalach   oldpeak  slope    ca  \
0    0.708333  1.000000  0.481132  0.244292  0.603053  0.370968    0.0  0.00   
1    0.166667  0.666667  0.339623  0.283105  0.885496  0.564516    0.0  0.00   
2    0.250000  0.333333  0.339623  0.178082  0.770992  0.225806    1.0  0.00   
3    0.562500  0.333333  0.245283  0.251142  0.816794  0.129032    1.0  0.00   
4    0.583333  0.000000  0.245283  0.520548  0.702290  0.096774    1.0  0.00   
..        ...       ...       ...       ...       ...       ...    ...   ...   
298  0.583333  0.000000  0.433962  0.262557  0.396947  0.032258    0.5  0.00   
299  0.333333  1.000000  0.150943  0.315068  0.465649  0.193548    0.5  0.00   
300  0.812500  0.000000  0.471698  0.152968  0.534351  0.548387    0.5  0.50   
301  0.583333  0.000000  0.339623  0.011416  0.335878  0.193548    0.5  0.25   
302  0.583333  0.333333  0.339623  0.251142  0.786260  0.000000    0.5  0.25   

         thal  
0    0.333333  
1    0.666667  
2    0.666667  
3    0.666667  
4    0.666667  
..        ...  
298  1.000000  
299  1.000000  
300  1.000000  
301  1.000000  
302  0.666667  

[303 rows x 9 columns]

adanya proses normalisasi ini berfungsi agar jarak antar data tidak terlalu jauh dan dalam MinMaxScaler ini jarak data hanya berkisar pada 0 dan 1

In [ ]:
Hasil = Hasil.drop(columns = dataNormalisasi)
Hasil = pd.concat([Hasil, hasilNormalisasi], axis=1)
Hasil

fbs  restecg  exang  sex  target       age        cp  trestbps      chol  \
0      1        0      0    1       1  0.708333  1.000000  0.481132  0.244292   
1      0        1      0    1       1  0.166667  0.666667  0.339623  0.283105   
2      0        0      0    0       1  0.250000  0.333333  0.339623  0.178082   
3      0        1      0    1       1  0.562500  0.333333  0.245283  0.251142   
4      0        1      1    0       1  0.583333  0.000000  0.245283  0.520548   
..   ...      ...    ...  ...     ...       ...       ...       ...       ...   
298    0        1      1    0       0  0.583333  0.000000  0.433962  0.262557   
299    0        1      0    1       0  0.333333  1.000000  0.150943  0.315068   
300    1        1      0    1       0  0.812500  0.000000  0.471698  0.152968   
301    0        1      1    1       0  0.583333  0.000000  0.339623  0.011416   
302    0        0      0    0       0  0.583333  0.333333  0.339623  0.251142   

      thalach   oldpeak  slope    ca      thal  
0    0.603053  0.370968    0.0  0.00  0.333333  
1    0.885496  0.564516    0.0  0.00  0.666667  
2    0.770992  0.225806    1.0  0.00  0.666667  
3    0.816794  0.129032    1.0  0.00  0.666667  
4    0.702290  0.096774    1.0  0.00  0.666667  
..        ...       ...    ...   ...       ...  
298  0.396947  0.032258    0.5  0.00  1.000000  
299  0.465649  0.193548    0.5  0.00  1.000000  
300  0.534351  0.548387    0.5  0.50  1.000000  
301  0.335878  0.193548    0.5  0.25  1.000000  
302  0.786260  0.000000    0.5  0.25  0.666667  

[303 rows x 14 columns]

Data hasil normalisasi di concat dengan data yang lain

In [ ]:
percent_amount_of_test_data = 0.3

*Menghitung Data*

X_train = data latih(nilai data)

X_test = data tes(nilai data)

y_train = data latih(kelas data)

y_tes = data tes (kelas data)

In [ ]:
matrices_X = Hasil.iloc[:,1:14].values
matrices_Y = Hasil.iloc[:,0].values

In [ ]:
X1 = Hasil.iloc[:,1:14].values
Y1 = Hasil.iloc[:, 0].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X1, Y1, test_size = percent_amount_of_test_data, random_state=0)

In [ ]:
X_train.shape

(212, 13)

In [ ]:
Y1

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
### Dictionary to store model and its accuracy

model_accuracy = OrderedDict()

### Dictionary to store model and its precision

model_precision = OrderedDict()

### Dictionary to store model and its recall

model_recall = OrderedDict()

Accuracy Model Naive Bayes

In [ ]:
naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)
Y_pred_nb = naive_bayes_classifier.predict(X_test)

cm = confusion_matrix(y_test, Y_pred_nb)

print('Confusion matrix for Gaussian Naive Bayes\n',cm)

naive_bayes_accuracy = round(100 * accuracy_score(y_test, Y_pred_nb), 2)
model_accuracy['Gaussian Naive Bayes'] = naive_bayes_accuracy

naive_bayes_precision = round(100 * precision_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_precision['Gaussian Naive Bayes'] = naive_bayes_precision

naive_bayes_recall = round(100 * recall_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_recall['Gaussian Naive Bayes'] = naive_bayes_recall

print('The accuracy of this model is {} %.'.format(naive_bayes_accuracy))
print('The precision of this model is {} %.'.format(naive_bayes_precision))
print('The recall of this model is {} %.'.format(naive_bayes_recall))

Confusion matrix for Gaussian Naive Bayes
 [[72  8]
 [ 9  2]]
The accuracy of this model is 81.32 %.
The precision of this model is 80.56 %.
The recall of this model is 81.32 %.


In [ ]:
Y_pred_nb

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0])

Y_pred_nb berasal dari prediksi nilai klasifikasi pada data teks

In [ ]:
clf = GaussianNB()
clf.fit(matrices_X, matrices_Y)
clf_pf = GaussianNB()
clf_pf.partial_fit(matrices_X, matrices_Y, np.unique(matrices_Y))

GaussianNB()

In [ ]:
FIRST_IDX = 0

In [ ]:
result_test_naive_bayes = clf_pf.predict([[1, 0,	0,	1,	0.708333,	1.000000,	0.481132,	0.244292,	0.603053,	0.370968,	0.0,	0.00,	0.333333]])[FIRST_IDX]
print(f"Data Baru SEX :  {result_test_naive_bayes} Pada metode Gaussian Naive Bayes model")

Data Baru SEX :  1 Pada metode Gaussian Naive Bayes model


Pada Model Naive Bayes mendapatkan hasil prediksi jika baris 0 termasuk pada Sex 1

#**KNN**#

In [ ]:
K = 3
knn = KNeighborsClassifier(n_neighbors = K)

knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

Pada proses ini langsung masuk ke proses prediksi klasifikasi dan nilai dari data tes dan kelas tes dengan menggunakan Model KNN

In [ ]:
Y_pred_knn = knn.predict(X_test)

In [ ]:
knn.score(X_test, y_test)

0.8571428571428571

In [ ]:
# Custom value to predict
result_test_knn = knn.predict([[1, 0,	0,	1,	0.708333,	1.000000,	0.481132,	0.244292,	0.603053,	0.370968,	0.0,	0.00,	0.333333]])
print(f"Data Baru Temasuk sex : {result_test_knn[FIRST_IDX]} Pada metode KNN model")

Data Baru Temasuk sex : 0 Pada metode KNN model


Sehingga jika menggunakan Model KNN data pada baris 0 termasuk pada Sex 0